FROM node:latest

WORKDIR /usr/src/app/

COPY package.json ./
# 配置taobao镜像
RUN npm config set registry https://registry.npm.taobao.org
RUN npm install --silent --no-cache

COPY ./ ./


CMD ["npm", "run", "start"]
